"""
Gem Proposals API Routes
Returns Gem trading proposals generated by the GemProposalEngine (runs in background).
Reads pre-calculated proposals from Redis.
"""
from fastapi import APIRouter
from app.core.logger import logger
from app.core.redis_client import get_redis_client
import json

router = APIRouter(prefix="/api/gem-proposals", tags=["gem"])

@router.get("/")
async def get_gem_proposals():
    """
    Returns GEM proposals generated by the GemProposalEngine.
    Reads 'gem:proposals' from Redis.
    """
    try:
        redis = get_redis_client().sync
        proposals_json = redis.get("gem:proposals")
        
        if proposals_json:
            proposals = json.loads(proposals_json)
        else:
            proposals = []
            
        logger.info(f"[GEM_API] Retrieved {len(proposals)} proposals from Redis gem:proposals")
        
        return {
            "success": True, 
            "count": len(proposals), 
            "data": proposals,
            "source": "redis_gem_engine"
        }
    except Exception as e:
        logger.error(f"[GEM_API] Error retrieving proposals from Redis: {e}", exc_info=True)
        return {"success": False, "error": str(e), "count": 0, "data": []}

@router.get("/inspect/{symbol}")
async def get_gem_inspection(symbol: str):
    """
    Returns detailed inspection data for a Gem symbol.
    Includes Truth Price source, Historical Volavs, and Group Calc Breakdown.
    """
    try:
        redis = get_redis_client().sync
        # Key set by gem_engine during proposal generation
        key = f"gem:inspect:{symbol}"
        data_json = redis.get(key)
        
        if data_json:
            data = json.loads(data_json)
            return {"success": True, "data": data}
        else:
            return {"success": False, "error": "No inspection data found. Wait for next cycle."}
            
    except Exception as e:
        logger.error(f"[GEM_API] Error inspecting {symbol}: {e}")
        return {"success": False, "error": str(e)}
